print("program starting")
brand = input ("Insert car brand: ")
model = input ("Insert car model:")
print('Car brand is "', brand, '" and the model is \'', model, "'.", sep="", end="\n")
print("Program ending.")